name: PHP Composer

on:
  push:
    branches: [ master, develop ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Validate composer.json and composer.lock
      run: composer validate

  #  - name: Clear Composer Cache
  #    run: composer clearcache

    - name: Install dependencies
      run: composer install --prefer-dist

    - name: Symfony Requirements Check
      run: vendor/bin/requirements-checker

    - name: Build test suite
      run: vendor/bin/codecept build

    - name: Create database
      run: bin/console doctrine:database:create --env=test

    - name: Validate database schema
      run: bin/console doctrine:schema:validate --skip-sync --env test

    - name: Run test suite
      run: vendor/bin/codecept run --steps --debug

  #  - name: Health Check
  #    run: bin/console monitor:health

    - name: PHP Metrics Report
      run: vendor/bin/phpmetrics --plugins=symfony .

    # Add a test script to composer.json, for instance: "test": "vendor/bin/phpunit"
    # Docs: https://getcomposer.org/doc/articles/scripts.md

    # - name: Run test suite
    #   run: composer run-script test

    # - name: Check CS
    #   run: vendor/bin/php-cs-fixer fix -v --dry-run --diff-format=udiff